name: Lucky Bella Tattoos
favicon: null
layout_spectrum: 0.5350659186951816
typography_spectrum: 0.26208090991713107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.26393480598926544
  lightness: 0.7529863906092942
  saturation: 0.2202216419391334
  rhythmicContrast: 0.6807870359625667
purpose: []
